dist: trusty
sudo: false
language: python
python:
 - "2.7"

branches:
  only:
    - automation

notifications:
  email:
    recipients:
    - info@mozilla.cz
    - mstanke@mozilla.cz
    on_success: change
    on_failure: always

install:
 - pip install mercurial
 - pip install hg-git

before_script: # Get ssh key from the secret variable
 - echo "$DEPLOY_KEY" | base64 -d > deploy_key
 - chmod 600 deploy_key
 - eval `ssh-agent -s`
 - ssh-add deploy_key
 - ssh-add -L

script:
 - bash ./push-central-to-github.sh

after_script: # Kill the ssh-agent
 - rm -f deploy_key
 - ssh-agent -k

cache:
  directories:
  - $HOME/.cache/pip
  - github_l10n-mozilla-central-cs

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
